// examples/vue-demo/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { Heart } from "lucide-vue-next";
import { MaterialCard } from "@material-cards/vue";

const isOpen = ref(false);
</script>

<template>
  <main style="max-width: 420px; margin: 40px auto; padding: 16px;">
    <MaterialCard
      color="orange"
      :is-open="isOpen"
      @open-change="(value) => (isOpen = value)"
      :card="{
        title: 'Vue Demo',
        subtitle: 'Material Card',
        description: 'Card Vue con stato controllato.',
        image: {
          src: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80',
          alt: 'Mountain'
        },
        actions: [{ id: 'fav', label: 'Preferiti', icon: Heart }],
        links: [{ label: 'Vue Docs', href: 'https://vuejs.org', target: '_blank' }]
      }"
    />
  </main>
</template>

// examples/next-demo/app/page.tsx
"use client";

import { Heart } from "lucide-react";
import { MaterialCard } from "@material-cards/react";

export default function HomePage() {
  return (
    <main style={{ maxWidth: 420, margin: "40px auto", padding: 16 }}>
      <MaterialCard
        color="teal"
        defaultOpen={false}
        card={{
          title: "Next Demo",
          subtitle: "Material Card",
          description: "Card React usata dentro Next.js.",
          image: {
            src: "https://images.unsplash.com/photo-1477506350614-975d8d6b6d65?auto=format&fit=crop&w=900&q=80",
            alt: "Landscape"
          },
          actions: [{ id: "fav", label: "Preferiti", Icon: Heart }],
          links: [{ label: "Docs", href: "https://nextjs.org", target: "_blank" }]
        }}
      />
    </main>
  );
}
